import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bdevore
 */
public class GUIHub extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdmin
     */
    CentralAPI api;
    String[] lNums;
    Object[][] dotmodel;
    Object[][] model;
    JCheckBox[] boxes;
    private String[][] months = {{"January", "February", "March", "April", "May","June","July","August","September","October","November","December"}
              ,{"01","02","03","04","05","06","07","08","09","10","11","12"}}; 
    
    public GUIHub(CentralAPI a) {
        initComponents();
        api = a;
        updateTable();
        organizeBoxes();
        paragraph.setEditable(false);
        aboutInfo.setEditable(false);
        setMonthDropdown();
        setDayDropdown();
        setYearDropdown();
        setDay();
        setMonth();
        setYear();
        newFirstName.setText(api.getUserInfo()[0]);
        newLastName.setText(api.getUserInfo()[1]);
        newPhone.setText(api.getUserInfo()[3]);
        newEmail.setText(api.getUserInfo()[4]);
    }
    private void setDay(){
        int index = Integer.valueOf((api.getUserInfo()[2].substring(2, 4)));
        System.out.println(index);
        Day.setSelectedIndex(index-1);
    }
    private void setMonth(){
        int index = Integer.valueOf((api.getUserInfo()[2].substring(0, 2)));
        System.out.println(index);
        Month.setSelectedIndex(index-1);
    }
    private void setYear(){
        int index = Integer.valueOf((api.getUserInfo()[2].substring(4, 8)));
        System.out.println(index);
        Year.setSelectedIndex(2015-index);
    }
    private void organizeBoxes() {
        boxes= new JCheckBox[7];
        boxes[0]= box0;
        boxes[1]= box1;
        boxes[2]= box2;
        boxes[3]= box3;
        boxes[4]= box4;
        boxes[5]= box5;
        boxes[6]= box6;
    }
    
    public void updateTable(){
        parseArray(api.getVault());
        if(showPassword.isSelected())
            VaultTable.setModel(new ReadOnlyTableModel(model , new String [] {"Status","Provider","Username", "Password", "Comments"}));
        else
            VaultTable.setModel(new ReadOnlyTableModel(dotmodel , new String [] {"Status","Provider","Username", "Password", "Comments"}));

    }
    
    
    
    private void parseArray(String[][] a){
        lNums= new String[a.length];
        model = new Object[a.length][a[0].length];
        dotmodel = new Object[a.length][a[0].length];
        boolean[] boxValues = api.loginStatus();
        for(int i=0;i<a.length;i++){
            lNums[i] = a[i][0]; 
        }
        for(int i=0;i<23;i++){
            model[i][0]=boxValues[i];
            dotmodel[i][0] = boxValues[i];
        }
        for(int i=0;i<a.length;i++){
            for(int j=1;j<a[i].length;j++){
                if(!showPassword.isSelected() && j==3)
                    dotmodel[i][j]= "••••••••••";
                else
                    dotmodel[i][j] = new String(a[i][j]);
                model[i][j] = new String(a[i][j]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Courses = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        aboutInfo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        updateInfoButton = new javax.swing.JButton();
        newFirstName = new javax.swing.JTextField();
        newLastName = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        deleteAccountButton = new javax.swing.JButton();
        Month = new javax.swing.JComboBox();
        Day = new javax.swing.JComboBox();
        Year = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        newPhone = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VaultTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        editAccount = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        launch = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        box0 = new javax.swing.JCheckBox();
        box1 = new javax.swing.JCheckBox();
        box2 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();
        box4 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        box5 = new javax.swing.JCheckBox();
        box6 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Launch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        paragraph = new javax.swing.JTextArea();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EZLogin");

        aboutInfo.setBackground(new java.awt.Color(240, 240, 240));
        aboutInfo.setColumns(20);
        aboutInfo.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        aboutInfo.setRows(5);
        aboutInfo.setText("EZLogin is a program designed and created by Beshoi Genidy,\nBen Devore, and Sam Given. Our aim was to create a\nprogram that would aid a user in making themselves present on\nthe internet, as well as easily allowing them to save whatever\naccount data needed. We hope to continue to grow the abilities\nof the program, to only further the capabilities of our users.");
        jScrollPane3.setViewportView(aboutInfo);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/logo small.PNG"))); // NOI18N

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Update Account Info");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("First Name");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Last Name");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setText("Email");

        updateInfoButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        updateInfoButton.setText("Update Info");
        updateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoButtonActionPerformed(evt);
            }
        });

        newFirstName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        newLastName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        newEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        deleteAccountButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        Month.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Day.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        Year.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setText("Birthdate");

        newPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel14.setText("Phone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(newFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(newLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(newPhone)))
                                    .addComponent(updateInfoButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(168, 168, 168))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(newFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(newLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateInfoButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Courses.addTab("My Account", jPanel2);

        VaultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provider", "Username", "Password", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VaultTable);
        if (VaultTable.getColumnModel().getColumnCount() > 0) {
            VaultTable.getColumnModel().getColumn(0).setResizable(false);
            VaultTable.getColumnModel().getColumn(1).setResizable(false);
            VaultTable.getColumnModel().getColumn(2).setResizable(false);
            VaultTable.getColumnModel().getColumn(3).setResizable(false);
        }

        addButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        editAccount.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        editAccount.setText("Edit");
        editAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        launch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        launch.setText("Launch Single Sign-on");
        launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel15.setText("Show Passwords");

        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(editAccount)
                        .addGap(18, 18, 18)
                        .addComponent(Save)
                        .addGap(18, 18, 18)
                        .addComponent(launch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showPassword)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(delete)
                    .addComponent(editAccount)
                    .addComponent(Save)
                    .addComponent(launch)
                    .addComponent(jLabel15)
                    .addComponent(showPassword))
                .addContainerGap())
        );

        Courses.addTab("Vault", jPanel3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Google.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/facebook_logo.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/twitterlogo.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Tumblrlogo.png"))); // NOI18N

        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/linkedinlogo.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/GitHub_logo.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Yahoo_Logo1.png"))); // NOI18N

        Launch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Launch.setText("Launch");
        Launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaunchActionPerformed(evt);
            }
        });

        paragraph.setBackground(new java.awt.Color(240, 240, 240));
        paragraph.setColumns(20);
        paragraph.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        paragraph.setRows(5);
        paragraph.setText("Select the corresponding boxes for \nwhich you would like to create a \nprofile on. The program will complete \nit for you as soon as you click launch.");
        jScrollPane2.setViewportView(paragraph);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(box5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(box6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Launch)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box1)
                                    .addComponent(box0)
                                    .addComponent(box2)
                                    .addComponent(box3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(box4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(95, 95, 95))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Launch)))
                .addGap(25, 25, 25))
        );

        Courses.addTab("Form Completion", jPanel6);

        close.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        close.setText("Log Out");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Courses)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(close)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Courses, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("EZLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaunchActionPerformed
        // TODO add your handling code here:
        int[] t = new int[7];
        for(int i=0; i<t.length;i++){
            if(boxes[i].isSelected())
            t[i]=1;
        }
        api.formCompletion(t);
    }//GEN-LAST:event_LaunchActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed

    private void editAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountActionPerformed
        // TODO add your handling code here:
        boolean cbox = true;
        if(VaultTable.getSelectedRow()!=-1){
           if(VaultTable.getModel().getValueAt(VaultTable.getSelectedRow(),0)==null || !((Boolean)VaultTable.getModel().getValueAt(VaultTable.getSelectedRow(),0))){
               cbox=false;
           }
           GUIVaultDialog dialog = new GUIVaultDialog(this,true,(VaultTable.getSelectedRow()<23), api, lNums[VaultTable.getSelectedRow()],model[VaultTable.getSelectedRow()],cbox);
           dialog.setVisible(true);
        }
    }//GEN-LAST:event_editAccountActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete from Vault?", JOptionPane.YES_NO_OPTION) ==0){
            if(VaultTable.getSelectedRow() >= 23){
                api.deleteFromVault(lNums[VaultTable.getSelectedRow()]); // add are you sure box
            }
            else if(VaultTable.getSelectedRow()!=-1){
                api.updateVault(lNums[VaultTable.getSelectedRow()], false, (String)model[VaultTable.getSelectedRow()][1], "","","");
            }
            updateTable();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:s
        GUIVaultDialog dialog = new GUIVaultDialog(this,true, api);
        dialog.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<23;i++){
            api.updateLoginSS(lNums[i], (boolean)VaultTable.getModel().getValueAt(i, 0));
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void launchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchActionPerformed
        // TODO add your handling code here:
        api.launchSS();
    }//GEN-LAST:event_launchActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        GUI g = new GUI();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUIPasswordChange pChange = new GUIPasswordChange(this,true,api);
        pChange.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void setDayDropdown(){
        String[] days = new String[31];
        for(int i=0;i<9;i++){
            days[i]= "0"+String.valueOf(i+1);
        }
        for(int i=9;i<31;i++){
            days[i]= String.valueOf(i+1);
        }
        Day.setModel(new javax.swing.DefaultComboBoxModel(days));
    }
    private void setYearDropdown(){
        String[] years = new String[116];
        int j=0;
        for(int i=2015;i>=1900;i--){
            years[j]= String.valueOf(i);
            j++;
        }
        Year.setModel(new javax.swing.DefaultComboBoxModel(years));
    }
    private void setMonthDropdown(){
        Month.setModel(new javax.swing.DefaultComboBoxModel(months[0]));
    }
    private void updateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoButtonActionPerformed
        // TODO add your handling code here:
        String bday = months[1][Month.getSelectedIndex()]+Day.getSelectedItem()+Year.getSelectedItem();
        boolean errorOccured=false;
        if(newFirstName.getText().length()>40 || newFirstName.getText().length()<1){
            ErrorMessageDialog fNameError = new ErrorMessageDialog(this,true,"Error: First name is not valid.");
            fNameError.setVisible(true);
            newFirstName.setText("");
            errorOccured=true;
        }
        if(newLastName.getText().length()>40 || newLastName.getText().length()<1){
            ErrorMessageDialog lNameError = new ErrorMessageDialog(this,true,"Error: Last name is not valid.");
            lNameError.setVisible(true);
            newLastName.setText("");
            errorOccured=true;
        }
        if(newEmail.getText().length()>200 || newEmail.getText().length()<1){
            ErrorMessageDialog emailError = new ErrorMessageDialog(this,true,"Error: Email is not valid.");
            emailError.setVisible(true);
            newEmail.setText("");
            errorOccured=true;
        }
        if(newPhone.getText().length()>10 || newPhone.getText().length()<1){
            ErrorMessageDialog phoneError = new ErrorMessageDialog(this,true,"Error: Phone number is not valid.");
            phoneError.setVisible(true);
            newPhone.setText("");
            errorOccured=true;
        }
        if(!errorOccured){
            api.about(newFirstName.getText(), newLastName.getText(), bday, newPhone.getText(), newEmail.getText());
            System.out.print("user updated");
        }
    }//GEN-LAST:event_updateInfoButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete Account?", JOptionPane.YES_NO_OPTION) ==0){
            api.deleteAccount();
            GUI g = new GUI();
            g.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHub(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Courses;
    private javax.swing.JComboBox Day;
    private javax.swing.JButton Launch;
    private javax.swing.JComboBox Month;
    private javax.swing.JButton Save;
    private javax.swing.JTable VaultTable;
    private javax.swing.JComboBox Year;
    private javax.swing.JTextArea aboutInfo;
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBox box0;
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box3;
    private javax.swing.JCheckBox box4;
    private javax.swing.JCheckBox box5;
    private javax.swing.JCheckBox box6;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton editAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton launch;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newFirstName;
    private javax.swing.JTextField newLastName;
    private javax.swing.JFormattedTextField newPhone;
    private javax.swing.JTextArea paragraph;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton updateInfoButton;
    // End of variables declaration//GEN-END:variables
}
